source "https://rubygems.org" do
  gem "github_changelog_generator", git: "https://github.com/github-changelog-generator/github-changelog-generator", ref: "9e0a959"
  gem "octokit", "~> 4"

  group :dev do
    gem "aws-sdk-dynamodb", "~> 1"
    gem "aws-sdk-lambda", "~> 1"
    gem "rufo", "~> 0.7"
  end

  group :test do
    gem "test-unit", "~> 3"
  end
end
