source 'https://rubygems.org' do
  gem 'github_changelog_generator', git: 'https://github.com/github-changelog-generator/github-changelog-generator', ref: '9e0a959'
  gem 'aws-sdk-sns', '~> 1'
  gem 'octokit', '~> 4'
end
