paths = Dir.glob("vendor/**/lib")
$LOAD_PATH.unshift(*paths)
require_relative 'changelog.rb'

$return = 0

$input_simple = %{
## [v0.1.2](https://github.com/foo/bar/tree/v0.1.2) (1234-56-78)

- foo
- bar
- baz

## [v0.1.1](https://github.com/foo/bar/tree/v0.1.1) (1234-56-78)

[Full Changelog](https://github.com/foo/bar/compare/v0.1.0...v0.1.1)

- Did the thing [\\#1](https://github.com/foo/bar/issues/1)
- Did the other thing [\\#2](https://github.com/foo/bar/pulls/2) ([foo](https://github.com/foo))

## [v0.1.0](https://github.com/foo/bar/tree/v0.1.0) (1234-56-78)

- foo
- bar
- baz

\* *This Changelog was automatically generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)*
}

$input_tricky = %{
## [v0.1.10](https://github.com/foo/bar/tree/v0.1.10) (1234-56-78)

- foo
- bar
- baz

## [v0.1.1](https://github.com/foo/bar/tree/v0.1.1) (1234-56-78)

[Full Changelog](https://github.com/foo/bar/compare/v0.1.0...v0.1.1)

- Did the thing [\\#1](https://github.com/foo/bar/issues/1)
- Did the other thing [\\#2](https://github.com/foo/bar/pulls/2) ([foo](https://github.com/foo))

\\* *This Changelog was automatically generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)*
}

$output = %{
## [v0.1.1](https://github.com/foo/bar/tree/v0.1.1) (1234-56-78)

[Diff since v0.1.0](https://github.com/foo/bar/compare/v0.1.0...v0.1.1)

- Did the thing (#1)
- Did the other thing (#2) ([foo](https://github.com/foo))
}.strip

def test_find_section
  output_simple = find_section($input_simple, 'v0.1.1')
  output_tricky = find_section($input_tricky, 'v0.1.1')
  assert($output, output_simple)
  assert($output, output_tricky)
end

def test_permutations
  perms = "foo".permutations
  expected = ["foo", "Foo"]
  assert(perms.length, 2)
  assert(perms.sort, expected.sort)

  perms = "foo bar".permutations
  expected = ["foo bar", "foobar", "foo-bar", "foo_bar", "Foo Bar", "FooBar", "Foo-Bar", "Foo_Bar"]
  assert(perms.length, 8)
  assert(perms.sort, expected.sort)
end

def run_tests
  test_find_section
  test_permutations
end

def assert(expected, observed)
  unless expected == observed
    puts 'Assertion failure'
    puts
    puts '=== Expected ==='
    puts expected
    puts '=== Observed ==='
    puts observed
    puts '================'
    puts caller
    $return += 1
  end
end

if $0 == __FILE__
  run_tests
  exit $return
end
