notifications: {email: false}
matrix:
  include:
    - language: go
      go: 1.12
      script: ./bin/test.sh github
    - language: ruby
      rvm: 2.5
      install: true
      script: ./bin/test.sh changelog
