notifications: {email: false}
matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      before_script: pip install mypy pytest
      script: ./bin/test.sh tabgot
    - language: ruby
      rvm: 2.5
      install: gem install bundler test-unit
      script: ./bin/test.sh changelog
