name: Julia TagBot
author: Chris de Graaf
description: Creates GitHub releases for your registered Julia packages
inputs:
  token:
    description: GitHub API token
    required: true
  registry:
    description: Owner/name of the registry repository
    required: false
    default: JuliaRegistries/General
  dispatch:
    description: Whether or not to create a repository dispatch event prior to making releases
    required: false
    default: false
runs:
  using: docker
  image: docker://ghcr.io/juliaregistries/tagbot:1.1.1
branding:
  icon: tag
  color: red
