name: Julia TagBot
author: Chris de Graaf
description: Creates GitHub releases for your registered Julia packages
inputs:
  token:
    description: GitHub API token
    required: true
  registry:
    description: Owner/name of the registry repository
    required: false
    default: JuliaRegistries/General
  branches:
    description: Whether or not to merge release branches
    required: false
    default: false
  dispatch:
    description: Whether or not to create a repository dispatch event prior to making releases
    required: false
    default: false
runs:
  using: docker
  image: docker://degraafc/tagbot:1
branding:
  icon: tag
  color: red
