name: Julia TagBot
author: Chris de Graaf
description: Creates GitHub releases for your registered Julia packages
inputs:
  token:
    description: GitHub API token
    required: true
  registry:
    description: URL of the registry
    required: false
    default: https://github.com/JuliaRegistries/General
  gpg-key:
    description: GPG key for tag signing
    required: false
runs:
  using: docker
  image: docker://ghcr.io/juliaregistries/tagbot:1.0.1
branding:
  icon: tag
  color: red
