name: Julia TagBot
author: Chris de Graaf
description: Creates GitHub releases for your registered Julia packages
inputs:
  token:
    description: GitHub API token
    required: true
  github-site:
    description: Base URL of the GitHub instance
    required: false
  github-api:
    description: Base URL of the GitHub instance's API
    required: false
  registry:
    description: Owner/name of the registry repository
    required: false
  gpg-key:
    description: GPG key for tag signing
    required: false
runs:
  using: docker
  image: docker://ghcr.io/juliaregistries/tagbot:1.0.7
branding:
  icon: tag
  color: red
