from typing import Any, Dict, Literal, Union, overload

class Lambda:
    def invoke(self, *, FunctionName: str, Payload: str) -> object: ...

class SSM:
    def get_parameter(
        self, *, Name: str, WithDecryption: bool = ...
    ) -> Dict[str, Any]: ...

@overload
def client(name: Literal["lambda"], *, region_name: str) -> Lambda: ...
@overload
def client(name: Literal["ssm"], *, region_name: str) -> SSM: ...
def client(name: str, *, region_name: str) -> Union[Lambda, SSM]: ...
