name: CI
on:
  push:
    branches:
      - main
      - master
      - cdg/julia  # TODO: Remove
  pull_request:
jobs:
  test_action:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t tagbot .
      - run: docker run -t tagbot julia -e 'using Pkg; Pkg.test()'
  test_web:
    name: Test web service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: |
          pip install -r requirements.txt pytest
          python -m pytest
        working-directory: web
  # TODO: Linting jobs.
