name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COLUMNS: 200
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12
      - run: pip install poetry
      - run: poetry install --all-extras
      - run: poetry run make test
  docker:
    runs-on: ubuntu-latest
    env:
      COLUMNS: 200
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Build Docker image
        run: docker build -t tagbot:test .
      - name: Install dependencies
        run: |
          docker run --name tagbot-deps --mount type=bind,source=$(pwd),target=/repo tagbot:test sh -c '
            pip install poetry && cd /repo && poetry install --all-extras'
          docker commit tagbot-deps tagbot:ready
          docker rm tagbot-deps
      - name: Run pytest
        run: docker run --rm --mount type=bind,source=$(pwd),target=/repo tagbot:ready sh -c 'cd /repo && poetry run make pytest'
      - name: Run black
        run: docker run --rm --mount type=bind,source=$(pwd),target=/repo tagbot:ready sh -c 'cd /repo && poetry run make black'
      - name: Run flake8
        run: docker run --rm --mount type=bind,source=$(pwd),target=/repo tagbot:ready sh -c 'cd /repo && poetry run make flake8'
      - name: Run mypy
        run: docker run --rm --mount type=bind,source=$(pwd),target=/repo tagbot:ready sh -c 'cd /repo && poetry run make mypy'


