name: Web Service Check
on:
  push:
    branches: [master]
    paths:
      - 'tagbot/web/**'
      - 'template.yaml'
      - 'samconfig.toml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'requirements.txt'
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'tagbot/web/**'
      - 'template.yaml'
      - 'samconfig.toml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'requirements.txt'
      - '.github/workflows/web.yml'
jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
      - run: pip install poetry poetry-plugin-export
      - name: Check requirements.txt is current
        run: |
          poetry export --extras web --output requirements.txt.check
          diff requirements.txt requirements.txt.check
      - uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
      - run: sam validate --lint
      - run: sam build
