name: Web Service Check
on:
  push:
    branches: [master]
    paths:
      - 'tagbot/web/**'
      - 'serverless.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'requirements.txt'
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'tagbot/web/**'
      - 'serverless.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'requirements.txt'
      - '.github/workflows/web.yml'
jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '20'
          cache: 'npm'
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
      - run: npm ci
      - run: pip install -r requirements.txt
      - name: Validate serverless config
        run: npx serverless package --stage dev
        env:
          GITHUB_TOKEN: dummy
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
